LOCATIONS = {
    0: "Doric's House",
    1: "Yanille",
    2: "Draynor",
    3: "Rimmington",
    4: "Grand Exchange",
    5: "Farming Guild",
    6: "Hosidius",
    7: "Harmony Island",
    8: "Gwenith",
    9: "Catherby",
    10: "Tree Gnome Stronghold",
    11: "Brimhaven",
    12: "Mos Le'Harmless",
    13: "Taverley",
    14: "Lumbridge Mill",
    15: "East Ardougne",
    16: "South of Varrock",
    17: "Miscellania",
}
